INSERT INTO PUBLIC.AUTHOR (ID, NAME) VALUES (1, 'Федор Достоевский');
INSERT INTO PUBLIC.AUTHOR (ID, NAME) VALUES (2, 'Эрих Мария Ремарк');
INSERT INTO PUBLIC.AUTHOR (ID, NAME) VALUES (3, 'Келли Макгонигал');

INSERT INTO PUBLIC.GENRE (ID, NAME) VALUES (1, 'Художественная литература');
INSERT INTO PUBLIC.GENRE (ID, NAME) VALUES (2, 'Литература по саморазвитию');

INSERT INTO PUBLIC.BOOK (ID, GENRE_ID, AUTHOR_ID, NAME, ISBN) VALUES (1, 1, 1, 'Идиот', '978-5-699-12014-7');
INSERT INTO PUBLIC.BOOK (ID, GENRE_ID, AUTHOR_ID, NAME, ISBN) VALUES (2, 1, 2, 'Три товарища', '978-5-699-12014-8');
INSERT INTO PUBLIC.BOOK (ID, GENRE_ID, AUTHOR_ID, NAME, ISBN) VALUES (3, 1, 2, 'Ночь в Лиссабоне', '978-5-699-12014-0');
INSERT INTO PUBLIC.BOOK (ID, GENRE_ID, AUTHOR_ID, NAME, ISBN) VALUES (4, 2, 3, 'Сила воли: Как развить и укрепить', '978-5-699-12015-5');